remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: Mduduzi Sibisi
description: Bookmark this to keep an eye on my project updates!
github:
  repository_url: https://github.com/OrigamiFolds/
